// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

/*
Package go_micro_service_product is a generated protocol buffer package.

It is generated from these files:
	proto/product/product.proto

It has these top-level messages:
	ProductInfo
	ProductImage
	ProductSize
	ProductSeo
	IDResponse
	IDRequest
	ProductResponse
	AllRequest
	AllResponse
*/
package go_micro_service_product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductInfo struct {
	Id                 int64           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ProductName        string          `protobuf:"bytes,2,opt,name=product_name,json=productName" json:"product_name,omitempty"`
	ProductSku         string          `protobuf:"bytes,3,opt,name=product_sku,json=productSku" json:"product_sku,omitempty"`
	ProductPrice       float64         `protobuf:"fixed64,4,opt,name=product_price,json=productPrice" json:"product_price,omitempty"`
	ProductDescription string          `protobuf:"bytes,5,opt,name=product_description,json=productDescription" json:"product_description,omitempty"`
	ProductCategoryId  int64           `protobuf:"varint,6,opt,name=product_category_id,json=productCategoryId" json:"product_category_id,omitempty"`
	ProductImage       []*ProductImage `protobuf:"bytes,7,rep,name=product_image,json=productImage" json:"product_image,omitempty"`
	ProductSize        []*ProductSize  `protobuf:"bytes,8,rep,name=product_size,json=productSize" json:"product_size,omitempty"`
	ProductSeo         *ProductSeo     `protobuf:"bytes,9,opt,name=product_seo,json=productSeo" json:"product_seo,omitempty"`
}

func (m *ProductInfo) Reset()                    { *m = ProductInfo{} }
func (m *ProductInfo) String() string            { return proto.CompactTextString(m) }
func (*ProductInfo) ProtoMessage()               {}
func (*ProductInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProductInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductInfo) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *ProductInfo) GetProductSku() string {
	if m != nil {
		return m.ProductSku
	}
	return ""
}

func (m *ProductInfo) GetProductPrice() float64 {
	if m != nil {
		return m.ProductPrice
	}
	return 0
}

func (m *ProductInfo) GetProductDescription() string {
	if m != nil {
		return m.ProductDescription
	}
	return ""
}

func (m *ProductInfo) GetProductCategoryId() int64 {
	if m != nil {
		return m.ProductCategoryId
	}
	return 0
}

func (m *ProductInfo) GetProductImage() []*ProductImage {
	if m != nil {
		return m.ProductImage
	}
	return nil
}

func (m *ProductInfo) GetProductSize() []*ProductSize {
	if m != nil {
		return m.ProductSize
	}
	return nil
}

func (m *ProductInfo) GetProductSeo() *ProductSeo {
	if m != nil {
		return m.ProductSeo
	}
	return nil
}

type ProductImage struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ImageName string `protobuf:"bytes,2,opt,name=image_name,json=imageName" json:"image_name,omitempty"`
	ImageCode string `protobuf:"bytes,3,opt,name=image_code,json=imageCode" json:"image_code,omitempty"`
	ImageUrl  string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl" json:"image_url,omitempty"`
}

func (m *ProductImage) Reset()                    { *m = ProductImage{} }
func (m *ProductImage) String() string            { return proto.CompactTextString(m) }
func (*ProductImage) ProtoMessage()               {}
func (*ProductImage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProductImage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductImage) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *ProductImage) GetImageCode() string {
	if m != nil {
		return m.ImageCode
	}
	return ""
}

func (m *ProductImage) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type ProductSize struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SizeName string `protobuf:"bytes,2,opt,name=size_name,json=sizeName" json:"size_name,omitempty"`
	SizeCode string `protobuf:"bytes,3,opt,name=size_code,json=sizeCode" json:"size_code,omitempty"`
}

func (m *ProductSize) Reset()                    { *m = ProductSize{} }
func (m *ProductSize) String() string            { return proto.CompactTextString(m) }
func (*ProductSize) ProtoMessage()               {}
func (*ProductSize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProductSize) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductSize) GetSizeName() string {
	if m != nil {
		return m.SizeName
	}
	return ""
}

func (m *ProductSize) GetSizeCode() string {
	if m != nil {
		return m.SizeCode
	}
	return ""
}

type ProductSeo struct {
	Id             int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SeoTitle       string `protobuf:"bytes,2,opt,name=seo_title,json=seoTitle" json:"seo_title,omitempty"`
	SeoKeywords    string `protobuf:"bytes,3,opt,name=seo_keywords,json=seoKeywords" json:"seo_keywords,omitempty"`
	SeoDescription string `protobuf:"bytes,4,opt,name=seo_description,json=seoDescription" json:"seo_description,omitempty"`
	SeoCode        string `protobuf:"bytes,5,opt,name=seo_code,json=seoCode" json:"seo_code,omitempty"`
}

func (m *ProductSeo) Reset()                    { *m = ProductSeo{} }
func (m *ProductSeo) String() string            { return proto.CompactTextString(m) }
func (*ProductSeo) ProtoMessage()               {}
func (*ProductSeo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProductSeo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductSeo) GetSeoTitle() string {
	if m != nil {
		return m.SeoTitle
	}
	return ""
}

func (m *ProductSeo) GetSeoKeywords() string {
	if m != nil {
		return m.SeoKeywords
	}
	return ""
}

func (m *ProductSeo) GetSeoDescription() string {
	if m != nil {
		return m.SeoDescription
	}
	return ""
}

func (m *ProductSeo) GetSeoCode() string {
	if m != nil {
		return m.SeoCode
	}
	return ""
}

type IDResponse struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
}

func (m *IDResponse) Reset()                    { *m = IDResponse{} }
func (m *IDResponse) String() string            { return proto.CompactTextString(m) }
func (*IDResponse) ProtoMessage()               {}
func (*IDResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IDResponse) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type IDRequest struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
}

func (m *IDRequest) Reset()                    { *m = IDRequest{} }
func (m *IDRequest) String() string            { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()               {}
func (*IDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IDRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type ProductResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ProductResponse) Reset()                    { *m = ProductResponse{} }
func (m *ProductResponse) String() string            { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()               {}
func (*ProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ProductResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AllRequest struct {
}

func (m *AllRequest) Reset()                    { *m = AllRequest{} }
func (m *AllRequest) String() string            { return proto.CompactTextString(m) }
func (*AllRequest) ProtoMessage()               {}
func (*AllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AllResponse struct {
	ProductInfo []*ProductInfo `protobuf:"bytes,1,rep,name=product_info,json=productInfo" json:"product_info,omitempty"`
}

func (m *AllResponse) Reset()                    { *m = AllResponse{} }
func (m *AllResponse) String() string            { return proto.CompactTextString(m) }
func (*AllResponse) ProtoMessage()               {}
func (*AllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AllResponse) GetProductInfo() []*ProductInfo {
	if m != nil {
		return m.ProductInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductInfo)(nil), "go.micro.service.product.ProductInfo")
	proto.RegisterType((*ProductImage)(nil), "go.micro.service.product.ProductImage")
	proto.RegisterType((*ProductSize)(nil), "go.micro.service.product.ProductSize")
	proto.RegisterType((*ProductSeo)(nil), "go.micro.service.product.ProductSeo")
	proto.RegisterType((*IDResponse)(nil), "go.micro.service.product.IDResponse")
	proto.RegisterType((*IDRequest)(nil), "go.micro.service.product.IDRequest")
	proto.RegisterType((*ProductResponse)(nil), "go.micro.service.product.ProductResponse")
	proto.RegisterType((*AllRequest)(nil), "go.micro.service.product.AllRequest")
	proto.RegisterType((*AllResponse)(nil), "go.micro.service.product.AllResponse")
}

func init() { proto.RegisterFile("proto/product/product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdb, 0x6e, 0xda, 0x40,
	0x10, 0xc5, 0xd0, 0x06, 0x3c, 0x10, 0x50, 0xb6, 0x2f, 0xdb, 0xa0, 0xaa, 0xd4, 0xe9, 0x85, 0x36,
	0x92, 0x23, 0xd1, 0x2f, 0xa0, 0xa1, 0x55, 0x51, 0xa4, 0x2a, 0x22, 0x8d, 0xfa, 0xd0, 0x07, 0x8b,
	0x7a, 0x27, 0x68, 0x85, 0xf1, 0xba, 0x5e, 0xd3, 0x8a, 0x7c, 0x4d, 0x7f, 0xa6, 0x7f, 0xd4, 0x0f,
	0xa8, 0x76, 0xbd, 0x6b, 0x5b, 0xbd, 0x00, 0x79, 0x82, 0x99, 0x33, 0x7b, 0x66, 0xe6, 0xcc, 0x11,
	0x40, 0x3f, 0x49, 0x45, 0x26, 0xce, 0x92, 0x54, 0xb0, 0x75, 0x98, 0xd9, 0x4f, 0x5f, 0x67, 0x09,
	0x5d, 0x08, 0x7f, 0xc5, 0xc3, 0x54, 0xf8, 0x12, 0xd3, 0x6f, 0x3c, 0x44, 0xdf, 0xe0, 0xde, 0xcf,
	0x06, 0xb4, 0x2f, 0xf3, 0xef, 0xd3, 0xf8, 0x46, 0x90, 0x2e, 0xd4, 0x39, 0xa3, 0xce, 0xc0, 0x19,
	0x36, 0x66, 0x75, 0xce, 0xc8, 0x13, 0xe8, 0x98, 0xd2, 0x20, 0x9e, 0xaf, 0x90, 0xd6, 0x07, 0xce,
	0xd0, 0x9d, 0xb5, 0x4d, 0xee, 0xc3, 0x7c, 0x85, 0xe4, 0x31, 0xd8, 0x30, 0x90, 0xcb, 0x35, 0x6d,
	0xe8, 0x0a, 0x30, 0xa9, 0xab, 0xe5, 0x9a, 0x9c, 0xc0, 0xa1, 0x2d, 0x48, 0x52, 0x1e, 0x22, 0xbd,
	0x37, 0x70, 0x86, 0xce, 0xcc, 0x12, 0x5f, 0xaa, 0x1c, 0x39, 0x83, 0x07, 0xb6, 0x88, 0xa1, 0x0c,
	0x53, 0x9e, 0x64, 0x5c, 0xc4, 0xf4, 0xbe, 0x66, 0x23, 0x06, 0x9a, 0x94, 0x08, 0xf1, 0xcb, 0x07,
	0xe1, 0x3c, 0xc3, 0x85, 0x48, 0x37, 0x01, 0x67, 0xf4, 0x40, 0x8f, 0x7e, 0x64, 0xa0, 0x73, 0x83,
	0x4c, 0x19, 0xb9, 0x28, 0xa7, 0xe0, 0xab, 0xf9, 0x02, 0x69, 0x73, 0xd0, 0x18, 0xb6, 0x47, 0xcf,
	0xfd, 0xff, 0x69, 0xe3, 0x5b, 0x5d, 0x54, 0x75, 0x31, 0xad, 0x8e, 0xc8, 0xfb, 0x52, 0x16, 0xc9,
	0x6f, 0x91, 0xb6, 0x34, 0xd7, 0xb3, 0x9d, 0x5c, 0x57, 0xfc, 0x16, 0x0b, 0xf5, 0x54, 0x40, 0xde,
	0x56, 0xd4, 0x43, 0x41, 0xdd, 0x81, 0x33, 0x6c, 0x8f, 0x9e, 0xee, 0x26, 0x42, 0x51, 0x6a, 0x8c,
	0xc2, 0xdb, 0x40, 0xa7, 0x3a, 0xee, 0x5f, 0x77, 0x7c, 0x04, 0xa0, 0xb7, 0xae, 0x5e, 0xd1, 0xd5,
	0x19, 0x7d, 0xc3, 0x02, 0x0e, 0x05, 0x43, 0x73, 0xc2, 0x1c, 0x3e, 0x17, 0x0c, 0x49, 0x1f, 0xf2,
	0x20, 0x58, 0xa7, 0x91, 0xbe, 0x9e, 0x3b, 0x6b, 0xe9, 0xc4, 0x75, 0x1a, 0x79, 0x9f, 0x0a, 0x07,
	0xe9, 0x85, 0xfe, 0xec, 0xdc, 0x07, 0x57, 0x49, 0x54, 0x6d, 0xdc, 0x52, 0x09, 0xdd, 0xd7, 0x82,
	0x95, 0xb6, 0x1a, 0x54, 0x5d, 0xbd, 0x1f, 0x0e, 0x40, 0xb9, 0xee, 0x3f, 0x89, 0x51, 0x04, 0x19,
	0xcf, 0xa2, 0x92, 0x18, 0xc5, 0x47, 0x15, 0x2b, 0xdf, 0x2a, 0x70, 0x89, 0x9b, 0xef, 0x22, 0x65,
	0xd2, 0x70, 0xb7, 0x25, 0x8a, 0x0b, 0x93, 0x22, 0x2f, 0xa0, 0xa7, 0x4a, 0xaa, 0x6e, 0xcb, 0x57,
	0xeb, 0x4a, 0x14, 0x55, 0xa7, 0x3d, 0x04, 0xc5, 0x9b, 0xcf, 0x98, 0xfb, 0xb1, 0x29, 0x51, 0xe8,
	0x11, 0x4f, 0x01, 0xa6, 0x93, 0x19, 0xca, 0x44, 0xc4, 0x52, 0xab, 0x58, 0x58, 0xcc, 0x4e, 0xea,
	0x5a, 0xdf, 0x30, 0xef, 0x15, 0xb8, 0xaa, 0xf8, 0xeb, 0x1a, 0x65, 0xb6, 0xab, 0xf6, 0x14, 0x7a,
	0x66, 0xf5, 0x82, 0x9d, 0x42, 0x73, 0x85, 0x52, 0x2a, 0xeb, 0x3a, 0xf9, 0x14, 0x26, 0xf4, 0x3a,
	0x00, 0xe3, 0x28, 0x32, 0xcc, 0xea, 0x1e, 0x3a, 0x32, 0xcf, 0x2a, 0x56, 0xe5, 0xf1, 0x8d, 0xa0,
	0xce, 0x9e, 0x56, 0x55, 0x3f, 0x07, 0x85, 0x55, 0x55, 0x30, 0xfa, 0xd5, 0x80, 0xa6, 0x01, 0xc9,
	0x67, 0x80, 0x31, 0x63, 0x36, 0xda, 0x8f, 0xed, 0x78, 0x8b, 0xad, 0x4b, 0x15, 0xbd, 0x1a, 0x09,
	0xa0, 0xf7, 0x8e, 0xc7, 0x96, 0xfd, 0xcd, 0x66, 0x3a, 0x21, 0x27, 0xdb, 0x9f, 0xea, 0xcd, 0x8f,
	0xf7, 0x1b, 0xc3, 0xab, 0x91, 0x10, 0x0e, 0xaf, 0x13, 0x36, 0xcf, 0xf0, 0x8e, 0x0b, 0xbc, 0xdc,
	0x59, 0x56, 0xd9, 0x02, 0xe1, 0x68, 0x82, 0x11, 0x16, 0x4d, 0xf6, 0xdf, 0xe3, 0x4e, 0x6d, 0x02,
	0xe8, 0x2a, 0xb1, 0xc6, 0x51, 0x64, 0x97, 0xd9, 0x22, 0x73, 0x69, 0x93, 0x6d, 0x62, 0x55, 0xec,
	0xe3, 0xd5, 0xbe, 0x1c, 0xe8, 0xff, 0x90, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x38, 0x67,
	0xfe, 0x8d, 0x62, 0x06, 0x00, 0x00,
}
